### ISSUE TITLE
Include module path in log message if explicit tag present

### ISSUE THREAD

**Issue by jdm** [Nercury/android_logger-rs#25]
Having used the android logger for a number of months now, I disagree with https://github.com/Nercury/android_logger-rs/issues/22#issuecomment-409182664 . I think including the module name in the message is helpful for understanding the context of various debug messages, especially when several modules are included in the output. It would be useful to include the module path in the final log message.

**Comment by jdm** [comment]
cc @paulrouget

**Comment by paulrouget** [comment]
Agreed.

In Servo, you can always remove [the tag override](https://github.com/servo/servo/blob/362a0d5e144b938873679cac8b09df506214653d/ports/libsimpleservo/src/jniapi.rs#L84). But there are 2 side effects: adb module filtering won't work because rust use `::` as a separator, and that the module path is truncated.

If we use a custom tag, we should show the module path in the message though. I have a working patch.
