### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by caiiiycuk** [Nercury/android_logger-rs#56]
Hi! I am trying to use your lib in my project, but it won't compile:
```
   Compiling android_logger v0.11.1
error: type parameters must be declared prior to const parameters
   --> /home/caiiiycuk/.cargo/registry/src/github.com-1ecc6299db9ec823/android_logger-0.11.1/src/lib.rs:437:33
    |
437 | fn uninit_array<const N: usize, T>() -> [MaybeUninit<T>; N] {
    |                -----------------^- help: reorder the parameters: lifetimes, then types, then consts: <T, const N: usize>
```

**Comment by Nercury** [comment]
@Nilstrieb Help

**Comment by Nilstrieb** [comment]
Earlier this year we changed it so that the order of generic parameters doesn't matter anymore. Previously, const generics had to come last. To fix the issue, update your compiler.

@Nercury In case you want to support these older compilers, you can just swap the order of the generics in the helper function.

**Comment by Nercury** [comment]
Thanks for explanation. No we don't have hands available to support and test old compilers. It's always possible to use older crate version.
